In [40]:
!pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: snscrape in /usr/local/lib/python3.9/dist-packages (0.6.2.20230320)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.9/dist-packages (from snscrape) (4.11.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from snscrape) (3.10.7)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.9/dist-packages (from snscrape) (2.27.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4->snscrape) (2.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->snscrape) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->snscrape) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->snscrape) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->snscrape) (1.7.1)

In [41]:
import pandas as pd
import numpy as np
import snscrape.modules.twitter as sntwitter
import datetime

In [57]:
def fetcher(comp, start, end):
  query = f'${comp} until:{end} since:{start}'
  lis = []
  limit = 50
  for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(lis) == limit:
      break
    else:
      try:
        if tweet.lang == 'en' and tweet.cashtags == [comp]: #and #tweet.viewCount > 10:
          lis.append([tweet.rawContent])
      except:
        pass
  data = pd.DataFrame(lis,columns= ['Content'])
  return data

In [59]:
data = fetcher('AVGO','2018-01-01','2018-01-02')
data

                                              Content
0   $5.30 Billion in Sales Expected for Broadcom L...
1   $5.30 Billion in Sales Expected for Broadcom L...
2   $5.30 Billion in Sales Expected for Broadcom L...
3   $5.30 Billion in Sales Expected for Broadcom L...
4   Weekly Investment Analysts’ Ratings Changes fo...
5   Weekly Investment Analysts’ Ratings Changes fo...
6   Weekly Investment Analysts’ Ratings Changes fo...
7   Weekly Investment Analysts’ Ratings Changes fo...
8   Broadcom $AVGO Upgraded at Vetr https://t.co/z...
9   Broadcom $AVGO Upgraded at Vetr https://t.co/R...
10  Broadcom $AVGO Upgraded at Vetr https://t.co/M...
11  Broadcom $AVGO Upgraded at Vetr https://t.co/z...

In [44]:
stock = pd.read_csv('stock_data.csv',index_col=0)
stock.iloc[0,0]

'2018-01-02 00:00:00'

In [60]:
temp = list(stock.iloc[:,0])
temp1 = []
temp2 = []
arr = []
for i in range(len(temp)):
  x = temp[i][:10]
  arr.append(int(x[:4]))
  arr.append(int(x[5:7]))
  arr.append(int(x[8:10]))
  x = datetime.date(arr[0],arr[1],arr[2])
  temp1.append(x)
  x = x+datetime.timedelta(days=1)
  temp2.append(x)
#print(temp)
stock['Next_Day'] = temp2
stock.iloc[:,0] = temp1

In [61]:
stock.head()

,0,1,2,3,4,5,6,7,Next_Day
0,2018-01-02,112.040001,116.110001,112.040001,114.480003,114.480003,187400.0,ICLR,2018-01-03
1,2018-01-02,114.489998,114.940002,113.660004,114.019997,114.019997,379800.0,ICLR,2018-01-03
2,2018-01-02,114.339996,114.739998,112.650002,113.910004,113.910004,422700.0,ICLR,2018-01-03
3,2018-01-02,114.220001,117.980003,113.629997,117.620003,117.620003,299000.0,ICLR,2018-01-03
4,2018-01-02,117.669998,117.989998,115.680000,117.370003,117.370003,277000.0,ICLR,2018-01-03

In [62]:
fetcher('AVGO',str(stock.iloc[0,0]),str(stock.iloc[0,-1]))

                                             Content
0  @stockchartscom Nice call on $AVGO. Seasonalit...
1  Quick drop in $AVGO - Option Trading Edge  htt...
2  #توصيات #أوبشن \nSymbol : $AVGO\n\nOption Type...
3                              $AVGO 267.13 long new
4  Not sure what to tweet lately. Today I'm too b...
5  'Broadcom ( $AVGO)' SUDDEN RISE to 263.93, tod...
6  Prudential Financial Inc. Has $325.35 Million ...
7  $AVGO Max Pain=260.00. Maturity=01/05/2018. #m...
8  Prudential Financial Inc. Has $325.35 Million ...

In [ ]:
temp = []
for i in range(len(stock)):
  data = fetcher("AMZN",stock.iloc[i,0],stock.iloc[i,-1])
  data = list(data.iloc[:,0])
  temp.append(data)
  print(i)
temp[0]

In [ ]:
a = fetcher('AMZN', '2020-01-02','2020-01-03')
list(a.iloc[:,0])

In [53]:
vars(a)['viewCount']

In [83]:
temp

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]